### ISSUE TITLE
pyinstaller build documentation & glibc 2.29 

### ISSUE THREAD

**Issue by arrowgent** [Heroic-Games-Launcher/heroic-gogdl#1]
https://github.com/Heroic-Games-Launcher/heroic-gogdl/blob/main/.github/workflows/build.yaml

do you have some documentation how i can build this?

this is all im getting so far

`pyinstaller --onefile --name gogdl ?? gogdl/cli.py`
it builds but unsuccessfully calls errors when run

```
heroic-gogdl/dist $ ./gogdl 
Traceback (most recent call last):
  File "gogdl/cli.py", line 35, in <module>
  File "gogdl/cli.py", line 16, in main
  File "gogdl/args.py", line 7, in init_parser
  File "argparse.py", line 1716, in add_subparsers
TypeError: __init__() got an unexpected keyword argument 'required'
[2028] Failed to execute script 'cli' due to unhandled exception!
```

issue im having is glibc 2.29 requirements in your CI build environment
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1015

**Comment by arrowgent** [comment]
ok line 7 done
`    subparsers = parser.add_subparsers(dest='command')`


./gogdl 
```
Traceback (most recent call last):
  File "gogdl/cli.py", line 35, in <module>
  File "gogdl/cli.py", line 18, in main
AttributeError: 'Namespace' object has no attribute 'token'
[17168] Failed to execute script 'cli' due to unhandled exception!
```
not as concerned about this

moving it into 
`$HOME/.local/bin/heroic_dist/resources/app.asar.unpacked/build/bin/linux`
replace gogdl here with compiled gogdl

./heroic
### **we good to go**

```
(20:16:18) INFO:    [Gog]:             Found 0 game(s) to update
(20:16:33) INFO:    [Gog]:             Installing 1207664623 with: /home/catbox/.local/bin/heroic_dist/resources/app.asar.unpacked/build/bin/linux/gogdl download 1207664623 --platform windows --path="/media/catbox/CrucialXTB/legendary_egs/games" --skip-dlcs --lang="English"  |& tee "/home/catbox/.config/heroic/GamesConfig/1207664623.log"
(20:16:34) INFO:    [Backend]:         Progress: 1207664623 /MiB/undefined
----
(20:17:36) INFO:    [Backend]:         Progress: 1207664623 56.89/305.31
MiB/3844464:01:59
(20:17:37) INFO:    [Backend]:         finished installing
```




**working on python3.6 (3.9 not required)
working on ubuntu 18.04 with libc6 2.27**


can this be fixed in the heroic yarn to compile heroic-gogdl when someone compiles it manually on their system?
currently it seems to pull the precompiled binary directly from somewhere instead of compiling it


thanks for your help

anything else i can help YOU with?

**Comment by imLinguin** [comment]
I applied the changes (`required=True`) on testing branch. 
We should test if gogdl compiled with older python and glibc, will run without issues on distros like Arch (with newer packages)

**Comment by arrowgent** [comment]
indeed.  i mean it should, its fairly backwards compatible but there could always be breakage against glibc 2.31 or newer

lets see

ubuntu 18.04 = glibc 2.27
ubuntu 20.04 = glibc 2.31
upcomming 22.04 = glibc 2.35
debian 10 = glibc 2.28
debian 11 = glibc 2.31
arch = glibc 2.35

**Comment by arrowgent** [comment]
i believe github still has ubuntu 18.04
https://www.actionsbyexample.com/job-matrix.html

https://github.com/Heroic-Games-Launcher/heroic-gogdl/blob/72caf1bc710b6d8c8024005cd48028934c1ae1e0/.github/workflows/build.yaml#L10


ex:
```
matrix:
--
os: [ubuntu-18.04]

```

**Comment by imLinguin** [comment]
We are now sticking to `Ubuntu 20.04`, we can't really get any lower since `Ubuntu 18.04` is being deprecated from actions. 

We'll use the oldest available one from now on.
